// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqllmxqikwftdzqrhjwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxbGxteHFpa3dmdGR6cXJoandmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDA1NDQsImV4cCI6MjA3MjU3NjU0NH0.-geuTr-_7zg4US0S3tPUkpS1GZckTVJMoeRkoU81Lmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});